# Custom Language File for Launcher Customizer

[ejs.app]
title = "Invergence RP Network"

[ejs.landing]
mediaGitHubURL = ""
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/ujHekxQDwZ"

[ejs.settings]
sourceGithubLink = "https://github.com/Yoda234/Inflexion"
supportLink = "https://github.com/Yoda234/Inflexion/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Invergence RP NetWork"
welcomeDescription = "Explore ici tous les mondes réunis sous le Invergence RP Network."
welcomeDescCTA = "Vous êtes à seulement quelques clics d’entrer dans l’univers d’Invergence RP Network."
