
[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "• Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Recherche d'actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Lanceur"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le jeu séparément du lanceur."
launchDetachedDesc = "Si le jeu n'est pas lancé séparément, fermer le lanceur fermera également le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods à insérer"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Remarque : les shaders nécessitent un équipement puissant pour fonctionner correctement. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un pack de shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "Mémoire maximale (RAM)"
minRAM = "Mémoire minimale (RAM)"
memoryDesc = "La mémoire recommandée est d'au moins 3 Go. Fixer des valeurs minimales et maximales identiques peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM lors de l'exécution. Ne pas inclure <em>-Xms</em> et <em>-Xmx</em>."
launcherTabHeaderText = "Paramètres du lanceur"
launcherTabHeaderDesc = "Options relatives au lanceur lui-même."
allowPrereleaseTitle = "Autoriser les préversions."
allowPrereleaseDesc = "Les préversions incluent de nouvelles fonctionnalités qui peuvent ne pas être entièrement testées ou intégrées.<br>Cela sera toujours vrai si vous utilisez une version préliminaire."
dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner le répertoire de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations locales de Java seront stockés dans le répertoire de données.<br>Les captures d'écran et sauvegardes de mondes sont stockées dans le dossier de configuration correspondant au serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Consulter les informations et notes de version actuelles."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console des outils de développement"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du lanceur"
launcherUpdatesHeaderDesc = "Télécharger, installer et examiner les mises à jour du lanceur."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Valeur requise"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue est survenue. Consultez la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur lors du lancement"
failureText = "Consultez la console (CTRL + Maj + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des informations système..."
noCompatibleJava = "Aucune<br>installation Java compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous devez disposer d'une installation 64 bits de Java {major}. Voulez-vous que nous installions une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Consultez la console (CTRL + Maj + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = 'Une installation valide de Java {major} x64 est requise pour lancer.'
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a un hash incorrect, le fichier peut être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Consultez la console (CTRL + Maj + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Consultez la console (CTRL + Maj + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation au lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n a pas pu être téléchargé correctement."
doneEnjoyServer = "Terminé. Profitez du serveur !"
checkConsoleForDetails = "Veuillez consulter la console (CTRL + Maj + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "Naviguer vers Westeros !"
joined = "Exploration du royaume !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "L'authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "La déconnexion Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner un compte"
selectedButton = "Compte sélectionné ✔"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher, vous devez être connecté à au moins un compte. Vous devrez vous reconnecter après.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Oui, je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Échec de l'activation<br>d'un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Préversion"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle préversion disponible"
downloadingButton = "Téléchargement..."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et exécutez le dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour..."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : Impossible de charger l'index de distribution"
fatalErrorMessage = "Une connexion n'a pas pu être établie avec nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'était disponible pour être chargée.<br><br>L'index de distribution est un fichier essentiel fournissant les dernières informations sur le serveur. Le launcher ne peut pas démarrer sans lui. Assurez-vous d'être connecté à Internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actualisation de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil non configuré"
noProfileDesc = 'Votre compte Microsoft na pas encore de profil Minecraft configuré. Si vous avez récemment acheté le jeu ou l avez obtenu via Xbox Game Pass, vous devez configurer votre profil sur <a href="https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n avez pas encore acheté le jeu, vous pouvez également le faire sur <a href="https://minecraft.net/\">Minecraft.net</a>.'
noXboxAccountTitle = "Erreur de connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'est associé à aucun compte Xbox."
xblBannedTitle = "Erreur de connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft est originaire d'un pays où Xbox Live n'est pas disponible ou est interdit."
under18Title = "Erreur de connexion :<br>Approbation parentale requise"
under18Desc = "Les comptes pour les utilisateurs de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Non trouvé"
notFoundDesc = "Le point de terminaison d'authentification n'a pas été trouvé. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur de connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez essayé de vous connecter avec un compte migré. Réessayez en utilisant l'e-mail du compte comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur de connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L'e-mail ou le mot de passe que vous avez entré est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur de connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion récentes avec ce compte. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur de connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d'accès fourni est invalide."
tokenHasProfileTitle = "Erreur de connexion :<br>Profil assigné au jeton"
tokenHasProfileDesc = "Le jeton d'accès a déjà un profil assigné. La sélection des profils n'est pas encore implémentée."
credentialsMissingTitle = "Erreur de connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur ou le mot de passe n'a pas été soumis ou le mot de passe contient moins de 3 caractères."
invalidSaltVersionTitle = "Erreur de connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non pris en charge"
unsupportedMediaTypeDesc = "Type de média non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur de connexion :<br>Compte migré"
accountGoneDesc = "Le compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur de connexion :<br>Inaccessible"
unreachableDesc = "Impossible de joindre les serveurs d'authentification. Assurez-vous qu'ils sont en ligne et que vous êtes connecté à Internet."
gameNotPurchasedTitle = "Erreur de connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = 'Le compte que vous essayez de connecter n a pas acheté une copie de Minecraft. Vous pouvez acheter une copie sur <a href="https://minecraft.net/\">Minecraft.net</a>'
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."
